"""Added Offer model

Revision ID: 88831eada96d
Revises: 
Create Date: 2024-04-07 18:42:58.529732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88831eada96d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount_requested', sa.Float(), nullable=True),
    sa.Column('amount_to_trade', sa.Float(), nullable=True),
    sa.Column('usd_to_lbp', sa.Boolean(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    # ### end Alembic commands ###
